const STORE='nexa-studio-v1';
const DEMO={clients:[{id:'c1',name:'Cliente demonstrativo A',status:'ACTIVE'},{id:'c2',name:'Cliente demonstrativo B',status:'LEAD'},{id:'c3',name:'Cliente demonstrativo C',status:'RECURRENT'}],projects:[{id:'p1',name:'ORBITA',type:'Identidade visual',stage:'Diagnóstico',status:'ACTIVE',client:'c1'},{id:'p2',name:'PULSE',type:'Experiência digital',stage:'Produção',status:'ACTIVE',client:'c2'},{id:'p3',name:'MOVE',type:'Campanha',stage:'Briefing',status:'LEAD',client:'c3'},{id:'p4',name:'FORMA',type:'Editorial',stage:'QA / Entrega',status:'ACTIVE',client:'c3'}],portfolio:[{id:'o1',name:'ORBITA',type:'Identidade / sistema visual',featured:true},{id:'o2',name:'PULSE',type:'Design digital / interface',featured:true},{id:'o3',name:'MOVE',type:'Comunicação / campanha',featured:false},{id:'o4',name:'FORMA',type:'Design editorial',featured:false}],qa:{}};
const stages=['Briefing','Diagnóstico','Proposta','Produção','QA / Entrega'];
const qaItems=[['strategy','Resolve o problema?'],['visual','Está visualmente consistente?'],['functional','Funciona no meio previsto?'],['technical','Arquivo tecnicamente correto?'],['license','Créditos e licenças revisados?'],['delivery','Entrega documentada?']];
let db=load();
function clone(x){return JSON.parse(JSON.stringify(x))}
function load(){try{return JSON.parse(localStorage.getItem(STORE))||clone(DEMO)}catch{return clone(DEMO)}}
function save(){normalize();localStorage.setItem(STORE,JSON.stringify(db));renderAll()}
function uid(p){return p+Date.now().toString(36)+Math.random().toString(36).slice(2,6)}
function esc(v=''){return String(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function clientName(id){return db.clients.find(c=>c.id===id)?.name||'Sem cliente'}
function projectCount(id){return db.projects.filter(p=>p.client===id).length}
function normalize(){db.clients.forEach(c=>c.projects=projectCount(c.id))}
function card(l,v){return `<div class="dash-card"><small>${l}</small><strong>${v}</strong></div>`}
function renderDashboard(){document.getElementById('dashboard-cards').innerHTML=card('Projetos ativos',String(db.projects.filter(p=>p.status==='ACTIVE').length).padStart(2,'0'))+card('Clientes',String(db.clients.length).padStart(2,'0'))+card('Cases',String(db.portfolio.length).padStart(2,'0'))}
function renderProjects(){document.getElementById('project-list').innerHTML=db.projects.length?db.projects.map(p=>`<div class="list-row"><span><b>${esc(p.name)}</b><small>${esc(p.type)} · ${esc(clientName(p.client))}</small></span><span class="tag">${esc(p.status)}</span><span>${esc(p.stage)}</span><div class="row-actions"><button data-edit="project:${p.id}">Editar</button><button data-delete="project:${p.id}">Excluir</button></div></div>`).join(''):'<div class="note">Nenhum projeto cadastrado.</div>'}
function renderClients(){document.getElementById('client-list').innerHTML=db.clients.length?db.clients.map(c=>`<div class="list-row"><span><b>${esc(c.name)}</b><small>${projectCount(c.id)} projeto(s)</small></span><span class="tag">${esc(c.status)}</span><span>Cliente</span><div class="row-actions"><button data-edit="client:${c.id}">Editar</button><button data-delete="client:${c.id}">Excluir</button></div></div>`).join(''):'<div class="note">Nenhum cliente cadastrado.</div>'}
function renderPortfolio(){document.getElementById('portfolio-list').innerHTML=db.portfolio.length?db.portfolio.map(c=>`<article class="portfolio-card"><small>CASE ${esc(c.id.slice(-3).toUpperCase())}</small><h3>${esc(c.name)}</h3><p>${esc(c.type)}</p><span class="tag">${c.featured?'FEATURED':'DRAFT'}</span><div class="row-actions"><button data-edit="portfolio:${c.id}">Editar</button><button data-delete="portfolio:${c.id}">Excluir</button></div></article>`).join(''):'<div class="note">Nenhum case cadastrado.</div>'}
function renderWorkflow(){document.getElementById('workflow-board').innerHTML=stages.map(s=>`<div class="workflow-col"><h3>${s}</h3>${db.projects.filter(p=>p.stage===s).map(p=>`<div class="workflow-card"><b>${esc(p.name)}</b><small>${esc(p.type)}</small><select data-stage="${p.id}">${stages.map(x=>`<option ${x===p.stage?'selected':''}>${x}</option>`).join('')}</select></div>`).join('')||'<small class="empty">Vazio</small>'}</div>`).join('')}
function renderQA(){const s=document.getElementById('qa-project-select');if(!db.projects.length){s.innerHTML='<option value="">Nenhum projeto cadastrado</option>';document.getElementById('qa-list').innerHTML='';document.getElementById('qa-progress').textContent='Cadastre um projeto para iniciar o QA.';return}const old=s.value;s.innerHTML=db.projects.map(p=>`<option value="${p.id}">${esc(p.name)} — ${esc(p.type)}</option>`).join('');if(old&&db.projects.some(p=>p.id===old))s.value=old;renderQAItems()}
function renderQAItems(){const id=document.getElementById('qa-project-select').value;if(!id){document.getElementById('qa-list').innerHTML='';document.getElementById('qa-progress').textContent='Selecione um projeto.';return}const state=db.qa[id]||{},el=document.getElementById('qa-list');el.innerHTML=qaItems.map(([k,l])=>`<label class="check"><input type="checkbox" data-qa="${k}" ${state[k]?'checked':''}><span>${l}</span></label>`).join('');const done=qaItems.filter(([k])=>state[k]).length;document.getElementById('qa-progress').textContent=`${done}/${qaItems.length} critérios concluídos · ${Math.round(done/qaItems.length*100)}%`}
function renderAll(){normalize();renderDashboard();renderProjects();renderClients();renderPortfolio();renderWorkflow();renderQA()}
function openForm(type,id=''){const target=document.getElementById(type+'-form');const list=type==='project'?db.projects:type==='client'?db.clients:db.portfolio;const c=list.find(x=>x.id===id);let h='';if(type==='project')h=`<form data-save-form="project" data-id="${c?.id||''}"><h3>${c?'Editar':'Novo'} projeto</h3><input name="name" placeholder="Nome do projeto" value="${esc(c?.name||'')}" required><input name="type" placeholder="Tipo / serviço" value="${esc(c?.type||'')}" required><select name="client" required>${db.clients.length?db.clients.map(x=>`<option value="${x.id}" ${x.id===c?.client?'selected':''}>${esc(x.name)}</option>`).join(''):'<option value="">Cadastre um cliente primeiro</option>'}</select><select name="stage">${stages.map(x=>`<option ${x===c?.stage?'selected':''}>${x}</option>`).join('')}</select><select name="status"><option ${c?.status==='ACTIVE'?'selected':''}>ACTIVE</option><option ${c?.status==='LEAD'?'selected':''}>LEAD</option><option ${c?.status==='DONE'?'selected':''}>DONE</option></select><button class="button button-fill" ${db.clients.length?'':'disabled'}>Salvar</button><button type="button" class="button button-line" data-close-form="project">Cancelar</button></form>`;if(type==='client')h=`<form data-save-form="client" data-id="${c?.id||''}"><h3>${c?'Editar':'Novo'} cliente</h3><input name="name" placeholder="Nome do cliente" value="${esc(c?.name||'')}" required><select name="status"><option ${c?.status==='LEAD'?'selected':''}>LEAD</option><option ${c?.status==='ACTIVE'?'selected':''}>ACTIVE</option><option ${c?.status==='RECURRENT'?'selected':''}>RECURRENT</option></select><button class="button button-fill">Salvar</button><button type="button" class="button button-line" data-close-form="client">Cancelar</button></form>`;if(type==='portfolio')h=`<form data-save-form="portfolio" data-id="${c?.id||''}"><h3>${c?'Editar':'Novo'} case</h3><input name="name" placeholder="Nome do case" value="${esc(c?.name||'')}" required><input name="type" placeholder="Categoria / descrição" value="${esc(c?.type||'')}" required><label class="check"><input name="featured" type="checkbox" ${c?.featured?'checked':''}> <span>Destacar no portfolio</span></label><button class="button button-fill">Salvar</button><button type="button" class="button button-line" data-close-form="portfolio">Cancelar</button></form>`;target.innerHTML=h;target.classList.remove('hidden')}
function closeForm(type){const t=document.getElementById(type+'-form');t.classList.add('hidden');t.innerHTML=''}
const toolText={briefing:'BRIEFING NEXA\n\n1. Contexto\n2. Problema / necessidade\n3. Objetivo\n4. Público\n5. Mensagem\n6. Referências\n7. Restrições\n8. Entregáveis\n9. Prazo\n10. Critérios de sucesso',diagnosis:'DIAGNÓSTICO NEXA\n\nContexto → problema → causa → oportunidade → direção estratégica → hipótese de solução → próximos passos.',proposal:'PROPOSTA NEXA\n\n1. Contexto\n2. Objetivo\n3. Solução proposta\n4. Escopo\n5. Entregáveis\n6. Cronograma\n7. Premissas\n8. Investimento\n9. Validade\n10. Aprovação',case:'CASE NEXA\n\nContexto → desafio → estratégia → processo → solução → aplicação → resultado → aprendizados.'};
document.addEventListener('DOMContentLoaded',()=>{const year=document.getElementById('year');if(year)year.textContent=new Date().getFullYear();const header=document.querySelector('.site-header');const scroll=()=>header&&header.classList.toggle('is-scrolled',scrollY>30);scroll();addEventListener('scroll',scroll,{passive:true});document.querySelectorAll('.tab').forEach(t=>t.addEventListener('click',()=>{const id=t.dataset.tab;document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));t.classList.add('active');document.querySelectorAll('.panel').forEach(p=>p.classList.toggle('active',p.id===id));history.replaceState(null,'','#'+id)}));const hash=location.hash.slice(1),initial=document.querySelector(`.tab[data-tab="${hash}"]`);if(initial)initial.click();renderAll();
document.addEventListener('click',e=>{const o=e.target.closest('[data-open-form]');if(o)openForm(o.dataset.openForm);const c=e.target.closest('[data-close-form]');if(c)closeForm(c.dataset.closeForm);const ed=e.target.closest('[data-edit]');if(ed){const [t,id]=ed.dataset.edit.split(':');openForm(t,id)}const del=e.target.closest('[data-delete]');if(del){const [t,id]=del.dataset.delete.split(':');if(t==='client'&&projectCount(id)>0){alert('Não é possível excluir este cliente enquanto houver projetos vinculados.');return}if(confirm('Excluir este registro?')){if(t==='project')db.projects=db.projects.filter(x=>x.id!==id);if(t==='client')db.clients=db.clients.filter(x=>x.id!==id);if(t==='portfolio')db.portfolio=db.portfolio.filter(x=>x.id!==id);delete db.qa[id];save()}}const tool=e.target.closest('[data-action]');if(tool)document.getElementById('tool-output').textContent=toolText[tool.dataset.action]});
document.addEventListener('submit',e=>{const f=e.target.closest('[data-save-form]');if(!f)return;e.preventDefault();const d=Object.fromEntries(new FormData(f).entries()),t=f.dataset.saveForm,id=f.dataset.id||uid(t[0]);if(t==='project'){if(!d.client){alert('Cadastre um cliente antes de criar um projeto.');return}const o={id,name:d.name,type:d.type,client:d.client,stage:d.stage,status:d.status};const i=db.projects.findIndex(x=>x.id===id);i>=0?db.projects[i]=o:db.projects.push(o)}if(t==='client'){const o={id,name:d.name,status:d.status};const i=db.clients.findIndex(x=>x.id===id);i>=0?db.clients[i]=o:db.clients.push(o)}if(t==='portfolio'){const o={id,name:d.name,type:d.type,featured:f.querySelector('[name=featured]').checked};const i=db.portfolio.findIndex(x=>x.id===id);i>=0?db.portfolio[i]=o:db.portfolio.push(o)}save();closeForm(t)});
document.addEventListener('change',e=>{if(e.target.matches('[data-stage]')){const p=db.projects.find(x=>x.id===e.target.dataset.stage);if(p){p.stage=e.target.value;save()}}if(e.target.matches('#qa-project-select'))renderQAItems();if(e.target.matches('[data-qa]')){const id=document.getElementById('qa-project-select').value;if(!id)return;db.qa[id]??={};db.qa[id][e.target.dataset.qa]=e.target.checked;save();renderQAItems()}});
document.getElementById('reset-data')?.addEventListener('click',()=>{if(confirm('Restaurar os dados demonstrativos?')){db=clone(DEMO);save()}});document.getElementById('export-data')?.addEventListener('click',()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(db,null,2)],{type:'application/json'}));a.download='nexa-studio-data.json';a.click()});document.getElementById('copy-tool')?.addEventListener('click',()=>navigator.clipboard?.writeText(document.getElementById('tool-output').textContent));document.getElementById('save-tool')?.addEventListener('click',()=>{const n=JSON.parse(localStorage.getItem('nexa-notes')||'[]');n.push({date:new Date().toISOString(),text:document.getElementById('tool-output').textContent});localStorage.setItem('nexa-notes',JSON.stringify(n));alert('Nota salva localmente.')})});